#!/bin/bash
# Auto-generated by grinding_warpage_2d.py
# Run: bash submit_all_grind_Silicon.sh

abaqus job=grind_Silicon_ws2000_f0200_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0200_d010' || echo '[FAIL] grind_Silicon_ws2000_f0200_d010'

abaqus job=grind_Silicon_ws2000_f0200_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0200_d020' || echo '[FAIL] grind_Silicon_ws2000_f0200_d020'

abaqus job=grind_Silicon_ws2000_f0200_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0200_d030' || echo '[FAIL] grind_Silicon_ws2000_f0200_d030'

abaqus job=grind_Silicon_ws2000_f0200_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0200_d050' || echo '[FAIL] grind_Silicon_ws2000_f0200_d050'

abaqus job=grind_Silicon_ws2000_f0300_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0300_d010' || echo '[FAIL] grind_Silicon_ws2000_f0300_d010'

abaqus job=grind_Silicon_ws2000_f0300_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0300_d020' || echo '[FAIL] grind_Silicon_ws2000_f0300_d020'

abaqus job=grind_Silicon_ws2000_f0300_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0300_d030' || echo '[FAIL] grind_Silicon_ws2000_f0300_d030'

abaqus job=grind_Silicon_ws2000_f0300_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0300_d050' || echo '[FAIL] grind_Silicon_ws2000_f0300_d050'

abaqus job=grind_Silicon_ws2000_f0500_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0500_d010' || echo '[FAIL] grind_Silicon_ws2000_f0500_d010'

abaqus job=grind_Silicon_ws2000_f0500_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0500_d020' || echo '[FAIL] grind_Silicon_ws2000_f0500_d020'

abaqus job=grind_Silicon_ws2000_f0500_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0500_d030' || echo '[FAIL] grind_Silicon_ws2000_f0500_d030'

abaqus job=grind_Silicon_ws2000_f0500_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0500_d050' || echo '[FAIL] grind_Silicon_ws2000_f0500_d050'

abaqus job=grind_Silicon_ws2000_f0800_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0800_d010' || echo '[FAIL] grind_Silicon_ws2000_f0800_d010'

abaqus job=grind_Silicon_ws2000_f0800_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0800_d020' || echo '[FAIL] grind_Silicon_ws2000_f0800_d020'

abaqus job=grind_Silicon_ws2000_f0800_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0800_d030' || echo '[FAIL] grind_Silicon_ws2000_f0800_d030'

abaqus job=grind_Silicon_ws2000_f0800_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws2000_f0800_d050' || echo '[FAIL] grind_Silicon_ws2000_f0800_d050'

abaqus job=grind_Silicon_ws4000_f0200_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0200_d010' || echo '[FAIL] grind_Silicon_ws4000_f0200_d010'

abaqus job=grind_Silicon_ws4000_f0200_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0200_d020' || echo '[FAIL] grind_Silicon_ws4000_f0200_d020'

abaqus job=grind_Silicon_ws4000_f0200_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0200_d030' || echo '[FAIL] grind_Silicon_ws4000_f0200_d030'

abaqus job=grind_Silicon_ws4000_f0200_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0200_d050' || echo '[FAIL] grind_Silicon_ws4000_f0200_d050'

abaqus job=grind_Silicon_ws4000_f0300_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0300_d010' || echo '[FAIL] grind_Silicon_ws4000_f0300_d010'

abaqus job=grind_Silicon_ws4000_f0300_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0300_d020' || echo '[FAIL] grind_Silicon_ws4000_f0300_d020'

abaqus job=grind_Silicon_ws4000_f0300_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0300_d030' || echo '[FAIL] grind_Silicon_ws4000_f0300_d030'

abaqus job=grind_Silicon_ws4000_f0300_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0300_d050' || echo '[FAIL] grind_Silicon_ws4000_f0300_d050'

abaqus job=grind_Silicon_ws4000_f0500_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0500_d010' || echo '[FAIL] grind_Silicon_ws4000_f0500_d010'

abaqus job=grind_Silicon_ws4000_f0500_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0500_d020' || echo '[FAIL] grind_Silicon_ws4000_f0500_d020'

abaqus job=grind_Silicon_ws4000_f0500_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0500_d030' || echo '[FAIL] grind_Silicon_ws4000_f0500_d030'

abaqus job=grind_Silicon_ws4000_f0500_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0500_d050' || echo '[FAIL] grind_Silicon_ws4000_f0500_d050'

abaqus job=grind_Silicon_ws4000_f0800_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0800_d010' || echo '[FAIL] grind_Silicon_ws4000_f0800_d010'

abaqus job=grind_Silicon_ws4000_f0800_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0800_d020' || echo '[FAIL] grind_Silicon_ws4000_f0800_d020'

abaqus job=grind_Silicon_ws4000_f0800_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0800_d030' || echo '[FAIL] grind_Silicon_ws4000_f0800_d030'

abaqus job=grind_Silicon_ws4000_f0800_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws4000_f0800_d050' || echo '[FAIL] grind_Silicon_ws4000_f0800_d050'

abaqus job=grind_Silicon_ws6000_f0200_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0200_d010' || echo '[FAIL] grind_Silicon_ws6000_f0200_d010'

abaqus job=grind_Silicon_ws6000_f0200_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0200_d020' || echo '[FAIL] grind_Silicon_ws6000_f0200_d020'

abaqus job=grind_Silicon_ws6000_f0200_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0200_d030' || echo '[FAIL] grind_Silicon_ws6000_f0200_d030'

abaqus job=grind_Silicon_ws6000_f0200_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0200_d050' || echo '[FAIL] grind_Silicon_ws6000_f0200_d050'

abaqus job=grind_Silicon_ws6000_f0300_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0300_d010' || echo '[FAIL] grind_Silicon_ws6000_f0300_d010'

abaqus job=grind_Silicon_ws6000_f0300_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0300_d020' || echo '[FAIL] grind_Silicon_ws6000_f0300_d020'

abaqus job=grind_Silicon_ws6000_f0300_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0300_d030' || echo '[FAIL] grind_Silicon_ws6000_f0300_d030'

abaqus job=grind_Silicon_ws6000_f0300_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0300_d050' || echo '[FAIL] grind_Silicon_ws6000_f0300_d050'

abaqus job=grind_Silicon_ws6000_f0500_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0500_d010' || echo '[FAIL] grind_Silicon_ws6000_f0500_d010'

abaqus job=grind_Silicon_ws6000_f0500_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0500_d020' || echo '[FAIL] grind_Silicon_ws6000_f0500_d020'

abaqus job=grind_Silicon_ws6000_f0500_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0500_d030' || echo '[FAIL] grind_Silicon_ws6000_f0500_d030'

abaqus job=grind_Silicon_ws6000_f0500_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0500_d050' || echo '[FAIL] grind_Silicon_ws6000_f0500_d050'

abaqus job=grind_Silicon_ws6000_f0800_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0800_d010' || echo '[FAIL] grind_Silicon_ws6000_f0800_d010'

abaqus job=grind_Silicon_ws6000_f0800_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0800_d020' || echo '[FAIL] grind_Silicon_ws6000_f0800_d020'

abaqus job=grind_Silicon_ws6000_f0800_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0800_d030' || echo '[FAIL] grind_Silicon_ws6000_f0800_d030'

abaqus job=grind_Silicon_ws6000_f0800_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws6000_f0800_d050' || echo '[FAIL] grind_Silicon_ws6000_f0800_d050'

abaqus job=grind_Silicon_ws8000_f0200_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0200_d010' || echo '[FAIL] grind_Silicon_ws8000_f0200_d010'

abaqus job=grind_Silicon_ws8000_f0200_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0200_d020' || echo '[FAIL] grind_Silicon_ws8000_f0200_d020'

abaqus job=grind_Silicon_ws8000_f0200_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0200_d030' || echo '[FAIL] grind_Silicon_ws8000_f0200_d030'

abaqus job=grind_Silicon_ws8000_f0200_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0200_d050' || echo '[FAIL] grind_Silicon_ws8000_f0200_d050'

abaqus job=grind_Silicon_ws8000_f0300_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0300_d010' || echo '[FAIL] grind_Silicon_ws8000_f0300_d010'

abaqus job=grind_Silicon_ws8000_f0300_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0300_d020' || echo '[FAIL] grind_Silicon_ws8000_f0300_d020'

abaqus job=grind_Silicon_ws8000_f0300_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0300_d030' || echo '[FAIL] grind_Silicon_ws8000_f0300_d030'

abaqus job=grind_Silicon_ws8000_f0300_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0300_d050' || echo '[FAIL] grind_Silicon_ws8000_f0300_d050'

abaqus job=grind_Silicon_ws8000_f0500_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0500_d010' || echo '[FAIL] grind_Silicon_ws8000_f0500_d010'

abaqus job=grind_Silicon_ws8000_f0500_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0500_d020' || echo '[FAIL] grind_Silicon_ws8000_f0500_d020'

abaqus job=grind_Silicon_ws8000_f0500_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0500_d030' || echo '[FAIL] grind_Silicon_ws8000_f0500_d030'

abaqus job=grind_Silicon_ws8000_f0500_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0500_d050' || echo '[FAIL] grind_Silicon_ws8000_f0500_d050'

abaqus job=grind_Silicon_ws8000_f0800_d010 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0800_d010' || echo '[FAIL] grind_Silicon_ws8000_f0800_d010'

abaqus job=grind_Silicon_ws8000_f0800_d020 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0800_d020' || echo '[FAIL] grind_Silicon_ws8000_f0800_d020'

abaqus job=grind_Silicon_ws8000_f0800_d030 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0800_d030' || echo '[FAIL] grind_Silicon_ws8000_f0800_d030'

abaqus job=grind_Silicon_ws8000_f0800_d050 cpus=1 interactive && \
  echo '[OK] grind_Silicon_ws8000_f0800_d050' || echo '[FAIL] grind_Silicon_ws8000_f0800_d050'

