"""
surrogate.py  —  JAX MLP surrogate for the AT2 forward model

Architecture (Novel C in thesis):
    Input:  (log_Gc, log_ell)  [2D parameter space, E fixed]
    Output: init_U             [crack initiation displacement]

Training data: generated by at2_simulator.run_forward on a Latin-hypercube
sample in (log_Gc, log_ell) space.

At inference time, surrogate.predict() runs in ~5µs vs ~1ms for full FD solve
→ ~200x speedup per likelihood evaluation.
With N=10^4 SMC particles × 20 transitions: 2×10^5 calls
  Full sim : 200s  (too slow for interactive SMC)
  Surrogate:   1s  (fast enough for 10-restart MAP or pilot SMC)

Usage:
    surr = AT2Surrogate()
    surr.fit(*generate_training_data(500, cfg=FAST))
    p = surr.crack_probability(params, theta_deg=45.0)
    ll = surr.log_likelihood(params, obs)
"""
from __future__ import annotations
from dataclasses import dataclass
import time
import numpy as np

import jax
import jax.numpy as jnp
import optax

from research.phasefield.at2_simulator import (
    PFParams, SimConfig, run_forward,
    gc_anisotropic, crack_probability as _sim_crack_prob,
    log_likelihood as _sim_log_likelihood,
)

# ─────────────────────────────────────────────────────────────────────────────
#  Training data
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class TrainingData:
    log_Gc:  np.ndarray   # (n,)
    log_ell: np.ndarray   # (n,)
    init_U:  np.ndarray   # (n,)   target
    peak_F:  np.ndarray   # (n,)   bonus target


def generate_training_data(
    n_samples:  int = 500,
    Gc_range:   tuple[float, float] = (2e-4, 3e-3),
    ell_range:  tuple[float, float] = (0.02,  0.10),
    E:          float = 1.0,
    cfg:        SimConfig | None = None,
    seed:       int = 0,
    verbose:    bool = False,
) -> TrainingData:
    """Sample (Gc, ell) uniformly in log-space, run AT2, collect init_U.

    Uses log-space sampling because init_U ~ sqrt(Gc/ell) (power-law scaling).
    """
    cfg_ = cfg or SimConfig()
    rng  = np.random.default_rng(seed)

    log_Gc_arr  = rng.uniform(np.log(Gc_range[0]),  np.log(Gc_range[1]),  n_samples)
    log_ell_arr = rng.uniform(np.log(ell_range[0]), np.log(ell_range[1]), n_samples)

    init_U_arr = np.empty(n_samples)
    peak_F_arr = np.empty(n_samples)

    t0 = time.perf_counter()
    for i in range(n_samples):
        p = PFParams(Gc=float(np.exp(log_Gc_arr[i])),
                     ell=float(np.exp(log_ell_arr[i])),
                     E=E, beta=0.0)
        r = run_forward(p, cfg_)
        init_U_arr[i] = r.init_U
        peak_F_arr[i] = r.peak_F

    if verbose:
        dt = time.perf_counter() - t0
        print(f"  {n_samples} samples in {dt:.2f}s  "
              f"({dt/n_samples*1e3:.2f} ms/sample)")

    return TrainingData(
        log_Gc=log_Gc_arr,
        log_ell=log_ell_arr,
        init_U=init_U_arr,
        peak_F=peak_F_arr,
    )


# ─────────────────────────────────────────────────────────────────────────────
#  JAX MLP (functional, JIT-compiled)
# ─────────────────────────────────────────────────────────────────────────────

def _init_params(layer_sizes: list[int], key: jax.Array) -> list[dict]:
    """He initialization for ReLU networks."""
    params = []
    for d_in, d_out in zip(layer_sizes[:-1], layer_sizes[1:]):
        key, k = jax.random.split(key)
        W = jax.random.normal(k, (d_in, d_out)) * jnp.sqrt(2.0 / d_in)
        b = jnp.zeros(d_out)
        params.append({"W": W, "b": b})
    return params


@jax.jit
def _forward(params: list[dict], x: jax.Array) -> jax.Array:
    """MLP forward pass. ReLU hidden layers, linear output."""
    h = x
    for layer in params[:-1]:
        h = jax.nn.relu(h @ layer["W"] + layer["b"])
    out = params[-1]
    return h @ out["W"] + out["b"]


@jax.jit
def _mse_loss(params, X, y):
    y_hat = _forward(params, X).squeeze(-1)
    return jnp.mean((y_hat - y) ** 2)


_grad_loss = jax.jit(jax.grad(_mse_loss))


# ─────────────────────────────────────────────────────────────────────────────
#  Surrogate model
# ─────────────────────────────────────────────────────────────────────────────

class AT2Surrogate:
    """JAX MLP surrogate for AT2 forward model.

    Input:  (log_Gc, log_ell)  — 2D, normalized internally
    Output: init_U (crack initiation displacement)

    After training, replace at2_simulator.run_forward calls:
        surr.predict_init_U(Gc, ell)        # single prediction
        surr.crack_probability(params, 45)  # probit, ~200x faster
        surr.log_likelihood(params, obs)    # full LL over obs
    """

    def __init__(self, hidden: list[int] | None = None):
        self.hidden    = hidden or [64, 64, 32]
        self._mlp      = None   # JAX params
        self._opt_state= None
        # Normalization stats (set during fit)
        self._X_mean: np.ndarray | None = None
        self._X_std:  np.ndarray | None = None
        self._y_mean: float = 0.0
        self._y_std:  float = 1.0
        # Reference init_U at each training Gc (for crack_probability)
        self._E: float = 1.0

    # ── Training ──────────────────────────────────────────────────────────────

    def fit(
        self,
        data:       TrainingData,
        n_epochs:   int   = 3000,
        lr:         float = 3e-3,
        batch_size: int   = 64,
        seed:       int   = 0,
        verbose:    bool  = True,
    ) -> list[float]:
        """Train MLP on TrainingData. Returns loss history (per epoch)."""
        X = np.column_stack([data.log_Gc, data.log_ell]).astype(np.float32)
        y = data.init_U.astype(np.float32)

        # Normalize
        self._X_mean = X.mean(axis=0)
        self._X_std  = X.std(axis=0) + 1e-8
        self._y_mean = float(y.mean())
        self._y_std  = float(y.std() + 1e-8)

        Xn = jnp.array((X - self._X_mean) / self._X_std)
        yn = jnp.array((y - self._y_mean) / self._y_std)

        layer_sizes = [2] + self.hidden + [1]
        key = jax.random.PRNGKey(seed)
        self._mlp = _init_params(layer_sizes, key)

        optimizer = optax.adam(lr)
        opt_state = optimizer.init(self._mlp)

        n = len(yn)
        rng = np.random.default_rng(seed)
        loss_hist = []

        @jax.jit
        def step(params, opt_state, Xb, yb):
            loss = _mse_loss(params, Xb, yb)
            grads = _grad_loss(params, Xb, yb)
            updates, opt_state_new = optimizer.update(grads, opt_state)
            params_new = optax.apply_updates(params, updates)
            return params_new, opt_state_new, loss

        for epoch in range(n_epochs):
            idx = rng.permutation(n)
            epoch_loss = 0.0
            n_batches = 0
            for start in range(0, n, batch_size):
                b = idx[start : start + batch_size]
                self._mlp, opt_state, loss = step(
                    self._mlp, opt_state, Xn[b], yn[b])
                epoch_loss += float(loss)
                n_batches += 1
            loss_hist.append(epoch_loss / n_batches)

            if verbose and (epoch + 1) % 500 == 0:
                print(f"  epoch {epoch+1:4d}/{n_epochs}  loss={loss_hist[-1]:.6f}")

        self._opt_state = opt_state
        return loss_hist

    # ── Prediction ────────────────────────────────────────────────────────────

    def _encode(self, log_Gc: float, log_ell: float) -> jax.Array:
        x = np.array([[log_Gc, log_ell]], dtype=np.float32)
        xn = (x - self._X_mean) / self._X_std
        return jnp.array(xn)

    def predict_init_U(self, Gc: float, ell: float) -> float:
        """Predict crack initiation displacement for isotropic params."""
        assert self._mlp is not None, "Call .fit() first"
        xn = self._encode(np.log(Gc), np.log(ell))
        yn = float(_forward(self._mlp, xn)[0, 0])
        return float(yn * self._y_std + self._y_mean)

    def predict_batch(self, Gc_arr: np.ndarray, ell_arr: np.ndarray) -> np.ndarray:
        """Batch predict init_U for arrays of (Gc, ell)."""
        assert self._mlp is not None
        log_Gc  = np.log(np.asarray(Gc_arr,  dtype=np.float32))
        log_ell = np.log(np.asarray(ell_arr, dtype=np.float32))
        X = np.column_stack([log_Gc, log_ell])
        Xn = jnp.array((X - self._X_mean) / self._X_std)
        yn = np.array(_forward(self._mlp, Xn)).squeeze(-1)
        return yn * self._y_std + self._y_mean

    # ── Drop-in replacements for at2_simulator functions ─────────────────────

    def crack_probability(
        self,
        params:      PFParams,
        theta_deg:   float,
        sigma_noise: float = 0.15,
    ) -> float:
        """Surrogate-accelerated crack_probability.

        Uses surrogate to predict init_U instead of running FD solver.
        Reference (isotropic U_ref) also from surrogate.
        """
        theta_rad = np.radians(theta_deg)
        Gc_eff = gc_anisotropic(theta_rad, params.Gc, params.beta)

        init_U_eff = self.predict_init_U(Gc_eff, params.ell)
        U_ref      = self.predict_init_U(params.Gc, params.ell)  # isotropic ref

        denom = max(sigma_noise * params.ell, 1e-14)
        z = (init_U_eff - U_ref) / denom
        from scipy.special import ndtr
        return float(np.clip(1.0 - ndtr(z), 1e-9, 1.0 - 1e-9))

    # ── Serialization ─────────────────────────────────────────────────────────

    def save(self, path: str) -> None:
        """Save weights + normalization stats to .npz (portable across machines)."""
        flat = {}
        for i, layer in enumerate(self._mlp):
            flat[f"layer_{i}_W"] = np.array(layer["W"])
            flat[f"layer_{i}_b"] = np.array(layer["b"])
        np.savez(path,
                 **flat,
                 X_mean=self._X_mean,
                 X_std=self._X_std,
                 y_mean=np.array([self._y_mean]),
                 y_std=np.array([self._y_std]),
                 hidden=np.array(self.hidden),
                 n_layers=np.array([len(self._mlp)]))

    @classmethod
    def load(cls, path: str) -> "AT2Surrogate":
        """Load a surrogate saved with .save() or train_surrogate_gpu.py."""
        d = np.load(path)
        hidden = list(d["hidden"].astype(int))
        surr = cls(hidden=hidden)
        n_layers = int(d["n_layers"][0])
        surr._mlp = [
            {"W": jnp.array(d[f"layer_{i}_W"]),
             "b": jnp.array(d[f"layer_{i}_b"])}
            for i in range(n_layers)
        ]
        surr._X_mean = d["X_mean"]
        surr._X_std  = d["X_std"]
        surr._y_mean = float(d["y_mean"][0])
        surr._y_std  = float(d["y_std"][0])
        return surr

    def log_likelihood(
        self,
        params:      PFParams,
        obs:         list[tuple[float, int]],
        sigma_noise: float = 0.15,
    ) -> float:
        """Surrogate Bernoulli-probit log-likelihood.

        Batches all forward passes into a single JAX call for speed.
        """
        from scipy.special import ndtr

        thetas = np.array([t for t, _ in obs])
        ys     = np.array([y for _, y in obs])
        Gc_effs = np.array([
            gc_anisotropic(np.radians(t), params.Gc, params.beta) for t in thetas
        ])
        ells = np.full(len(thetas), params.ell)

        # Single batch call: N obs + 1 reference
        Gc_all  = np.concatenate([Gc_effs, [params.Gc]])
        ell_all = np.concatenate([ells,    [params.ell]])
        init_U_all = self.predict_batch(Gc_all, ell_all)

        init_U_obs = init_U_all[:-1]
        U_ref      = init_U_all[-1]

        denom = max(sigma_noise * params.ell, 1e-14)
        z = (init_U_obs - U_ref) / denom
        p = np.clip(1.0 - ndtr(z), 1e-9, 1.0 - 1e-9)
        return float(np.sum(ys * np.log(p) + (1 - ys) * np.log(1.0 - p)))


# ─────────────────────────────────────────────────────────────────────────────
#  Benchmark utility
# ─────────────────────────────────────────────────────────────────────────────

def benchmark_speedup(
    surr:     AT2Surrogate,
    params:   PFParams,
    obs:      list[tuple[float, int]],
    cfg:      SimConfig | None = None,
    n_repeat: int = 20,
) -> dict:
    """Measure and report speedup: surrogate vs full simulator."""
    import time

    # Full simulator timing
    t0 = time.perf_counter()
    for _ in range(n_repeat):
        ll_sim = _sim_log_likelihood(params, obs, cfg=cfg)
    t_sim = (time.perf_counter() - t0) / n_repeat

    # Surrogate timing
    t0 = time.perf_counter()
    for _ in range(n_repeat):
        ll_surr = surr.log_likelihood(params, obs)
    t_surr = (time.perf_counter() - t0) / n_repeat

    speedup = t_sim / max(t_surr, 1e-9)
    ll_error = abs(ll_sim - ll_surr)

    return {
        "t_sim_ms":    t_sim   * 1e3,
        "t_surr_ms":   t_surr  * 1e3,
        "speedup":     speedup,
        "ll_sim":      ll_sim,
        "ll_surr":     ll_surr,
        "ll_abs_error":ll_error,
    }


# ─────────────────────────────────────────────────────────────────────────────
#  Demo
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    from research.phasefield.at2_simulator import generate_synthetic_dataset

    CFG  = SimConfig(n_elem=100, n_steps=80, u_max_factor=5.0)
    TRUE = PFParams(Gc=8e-4, ell=0.04, E=1.0, beta=-0.40)

    print("=== C: AT2 DeepONet-style surrogate ===\n")

    print("1. Generate training data (500 samples) ...")
    data = generate_training_data(500, cfg=CFG, verbose=True)
    print(f"   init_U range: [{data.init_U.min():.4f}, {data.init_U.max():.4f}]")

    print("\n2. Train surrogate (3-layer MLP, JAX+Adam) ...")
    surr = AT2Surrogate(hidden=[128, 128, 64])
    loss = surr.fit(data, n_epochs=5000, lr=2e-3, verbose=True)
    print(f"   Final loss: {loss[-1]:.6f}")

    print("\n3. Accuracy check (holdout) ...")
    test_data = generate_training_data(100, cfg=CFG, seed=99, verbose=False)
    pred = surr.predict_batch(
        np.exp(test_data.log_Gc), np.exp(test_data.log_ell))
    rel_err = np.abs(pred - test_data.init_U) / (test_data.init_U + 1e-12)
    print(f"   Mean relative error: {rel_err.mean()*100:.2f}%")
    print(f"   Max  relative error: {rel_err.max()*100:.2f}%")

    print("\n4. Speedup benchmark ...")
    obs = generate_synthetic_dataset(TRUE, theta_list=list(np.arange(0,91,15.0)),
                                     cfg=CFG, seed=0)
    bm = benchmark_speedup(surr, TRUE, obs, cfg=CFG, n_repeat=10)
    print(f"   Full sim:   {bm['t_sim_ms']:.2f} ms/LL")
    print(f"   Surrogate:  {bm['t_surr_ms']:.3f} ms/LL")
    print(f"   Speedup:    {bm['speedup']:.0f}x")
    print(f"   LL error:   {bm['ll_abs_error']:.4f}  (sim={bm['ll_sim']:.4f}  surr={bm['ll_surr']:.4f})")

    print("\n5. Crack probability sweep (surrogate vs simulator) ...")
    thetas = np.arange(0, 91, 15)
    print(f"  {'theta':>6}  {'p_sim':>6}  {'p_surr':>6}  {'|diff|':>6}")
    for t in thetas:
        p_sim  = _sim_crack_prob(TRUE, float(t), cfg=CFG)
        p_surr = surr.crack_probability(TRUE, float(t))
        print(f"  {t:6.0f}  {p_sim:6.3f}  {p_surr:6.3f}  {abs(p_sim-p_surr):6.3f}")
